apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubit
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: KUBIT_WATCHED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
