kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubit
subjects:
  - kind: ServiceAccount
    name: kubit
    namespace: kubit
roleRef:
  kind: ClusterRole
  name: kubit
  apiGroup: rbac.authorization.k8s.io
