---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubit
rules:
  # the kubit operator is controlled by appinstance resources and needs to be able to update
  # the status and update the spec.
  - apiGroups:
      - kubecfg.dev
    resources:
      - appinstances
      - appinstances/status
      - appinstances/spec
      - appinstances/finalizers
    verbs:
      - get
      - patch
      - list
      - update
      - watch
  # kubit operator needs to spawn an instance-specific applier that runs in the target namespace
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - patch
      - get
      - list
      - delete
      - watch
  # The kubit operator needs to access the image pull secret references by the AppInstance CR so it
  # can access the package metadata and validate the spec json schema.
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  # The instance specific applier job needs to have permissions
  # to create resources in the target namespace. The kubit operator will create
  # instance-specific RBAC rules for the applier job to use.
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - patch
      - get
      - delete
  # the kubit operator needs to be able to read logs from the instance-specific applier
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - list
      - get
