---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubit
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubecfg.dev
  resources:
  - appinstances
  - appinstances/status
  - appinstances/spec
  - appinstances/finalizers
  verbs:
  - get
  - patch
  - list
  - update
  - watch
