apiVersion: v1
kind: Namespace
metadata:
  name: kubit
  labels:
    control-plane: kubit
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: kubit
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kubit
    app.kubernetes.io/part-of: kubit
    app.kubernetes.io/managed-by: kustomize
