apiVersion: kubecfg.dev/v1alpha1
kind: AppInstance
metadata:
  name: demo
spec:
  package:
    image: gcr.io/mkm-cloud/package-demo:v1
    apiVersion: mkmik.pub/v1alpha1
    spec:
      foo: bar
      nested:
        stuff:
          - name: foo
          - name: bar
