name: Check actions

on:
  push:

jobs:
  check-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: |
            action-validator 0.5.3

      - name: Lint Actions
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}
