name: pack/push package demo
on:
  push:
    branches: ["main"]
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'


jobs:
  push_package_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
      - name: Login to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install kubecfg
        run: go install github.com/kubecfg/kubecfg@latest
      - name: Check version
        run: kubecfg version
      - name: Run kubecfg pack
        run: kubecfg pack --alpha ghcr.io/kubecfg/kubit/package-demo:v1 tests/fixtures/shell.jsonnet
