name: pack/push package demo
on:
  push:
    branches: ["main"]
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'


jobs:
  push_package_demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3
      - name: Login to GHCR
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install kubecfg
        run: go install github.com/kubecfg/kubecfg@latest
      - name: Check version
        run: kubecfg version
      - name: Run kubecfg pack
        run: kubecfg pack --alpha ghcr.io/kubecfg/kubit/package-demo:v1 tests/fixtures/shell.jsonnet
