name: Rust

on:
  push:
    branches: ["main"]
    tags:
      - v*.*.*
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: Swatinem/rust-cache@dd05243424bd5c0e585e4b55eb2d7615cdd32f1f # v2
      - name: Format
        run: cargo fmt --all --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build
      - name: Generate
        run: cargo run -- manifests --crd-dir kustomize/crd/bases
      - name: Diff
        run: test -z "$(git status --porcelain)" || (echo 'Changes detected after generating manifests'; git status; git --no-pager diff; false)
      - name: Run tests
        run: cargo test

  pack:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Set up Depot Docker Build
        uses: depot/setup-action@v1
      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Build
        uses: depot/build-push-action@v1
        with:
          project: vz2l70b5lw
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/kubecfg/kubit:latest
      - name: Push
        uses: depot/build-push-action@v1
        with:
          project: vz2l70b5lw
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kubecfg/kubit:latest
        if: github.event_name != 'pull_request'

  release:
    needs: [pack, build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Set up Depot Docker Build
        uses: depot/setup-action@v1
      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create_release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # renovate: tag=v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
      - name: release_image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          project: vz2l70b5lw
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kubecfg/kubit:${{ github.ref_name }}
